name: Waka Readme

on:
  schedule:
    # Runs at UTS+8 00:00
    - cron: '00 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE : "True"
          SHOW_OS : "True"
          SHOW_TIMEZONE : "True"
          SHOW_EDITORS : "True"
